version: '3.8'

services:
  php:   # ✅ Ce nom doit être exactement "php"
    build: .
    container_name: php
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
    networks:
      - symfony

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./jenkins/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - symfony

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony

networks:
  symfony:

volumes:
  db_data:
